# -*- coding: utf-8 -*-
"""Untitled25.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18ico-ZkYDK1mnZq6m67QSSEVD5VqEQ7J
"""

'''1. Write a Python program to handle a ZeroDivisionError exception when dividing a number by zero.'''

try:
    num1 = int(input("Enter numerator: "))
    num2 = int(input("Enter denominator: "))

    result = num1 / num2
    print("Result:", result)

except ZeroDivisionError:
    print("Error: Cannot divide by zero.")

'''2. Write a Python program that prompts the user to input an integer
and raises a ValueError exception if the input is not a valid integer.'''

try:
    num = int(input("Enter an integer: "))
    print("You entered:", num)

except ValueError:
    print("Error: Invalid input! Please enter a valid integer.")

'''3. Write a Python program that opens a file and handles a FileNotFoundError exception if the file does not exist.'''


try:
    file = open("data.txt", "r")
    content = file.read()
    print(content)
    file.close()

except FileNotFoundError:
    print("Error: File does not exist.")

'''4. Write a Python program that prompts the user to input two numbers and raises a TypeError exception if the inputs are not numerical.'''

try:
    num1 = input("Enter first number: ")
    num2 = input("Enter second number: ")

    # check if inputs are numeric
    if not num1.isnumeric() or not num2.isnumeric():
        raise TypeError("Inputs must be numerical")

    num1 = int(num1)
    num2 = int(num2)

    result = num1 + num2
    print("Sum:", result)

except TypeError as e:
    print("Error:", e)

'''5. Write a Python program that opens a file and handles a PermissionError exception if there is a permission issue.'''
try:
    file = open("data.txt", "r")
    content = file.read()
    print(content)
    file.close()

except PermissionError:
    print("Error: You do not have permission to access this file.")

'''6. Write a Python program that executes an operation on a list and handles an IndexError exception if the index is out of range.'''

try:
    numbers = [10, 20, 30, 40, 50]

    index = int(input("Enter index number: "))
    print("Element at index", index, "is:", numbers[index])

except IndexError:
    print("Error: Index out of range.")

'''7. Write a Python program that executes division and handles an ArithmeticError exception if there is an arithmetic error.'''

try:
    num1 = int(input("Enter first number: "))
    num2 = int(input("Enter second number: "))

    result = num1 / num2
    print("Result:", result)

except ArithmeticError:
    print("Arithmetic error occurred during division.")

