# -*- coding: utf-8 -*-
"""FileIOAssignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iiHVexjxzfMEPT1ADWoqRTDcIz-ZF1sk
"""

# Create sample.txt with some content
with open("Text.txt.txt", "w") as f:
    f.write("This is a sample text file.\n")
    f.write("It has multiple lines.\n")
    f.write("And will be read by the program.")

# Original code to read the entire text file
file = open("Text.txt.txt", "r")
content = file.read()
print(content)
file.close()

'''2. Write a Python program to read first n lines of a file.'''


n = int(input("Enter number of lines to read: "))

with open("Text.txt.txt", "r") as file:
    for i in range(n):
        line = file.readline()
        if line == "":
            break
        print(line, end="")

'''3. Write a Python program to append text to a file and display the text.'''

# append text to file
with open("Text.txt.txt", "a") as file:
    text = input("Enter text to append: ")
    file.write(text + "\n")

# display file content
with open("Text.txt.txt", "r") as file:
    print("\nFile Content:")
    print(file.read())

'''4. Write a Python program to read last n lines of a file.'''

n = int(input("Enter number of last lines to read: "))

with open("Text.txt.txt", "r") as file:
    lines = file.readlines()
    last_lines = lines[-n:]

for line in last_lines:
    print(line, end="")

'''4. Write a Python program to read last n lines of a file.'''


n = int(input("Enter number of last lines to read: "))

with open("Text.txt.txt", "r") as file:
    lines = file.readlines()
    last_lines = lines[-n:]

for line in last_lines:
    print(line, end="")

'''5. Write a Python program to read a file line by line and store it into a list.'''

lines_list = []

with open("Text.txt.txt", "r") as file:
    for line in file:
        lines_list.append(line.strip())

print("Lines stored in list:")
print(lines_list)

'''6. Write a Python program to read a file line by line store it into a variable.'''

content = ""

with open("Text.txt.txt", "r") as file:
    for line in file:
        content += line

print("File Content:")
print(content)

'''7. Write a python program to find the longest words.'''

sentence = input("Enter a sentence: ")

words = sentence.split()

max_len = max(len(word) for word in words)

print("Longest word(s):")
for word in words:
    if len(word) == max_len:
        print(word)

'''8. Write a Python program to count the number of lines in a text file.'''

count = 0

with open("Text.txt.txt", "r") as file:
    for line in file:
        count += 1

print("Number of lines in file:", count)

'''9. Write a Python program to count the frequency of words in a file.'''

with open("Text.txt.txt", "r") as file:
    text = file.read()

words = text.split()
word_freq = {}

for word in words:
    if word in word_freq:
        word_freq[word] += 1
    else:
        word_freq[word] = 1

print("Word Frequency:")
for word, count in word_freq.items():
    print(word, ":", count)

'''10. Write a Python program to get the file size of a plain file.'''

import os

file_name = "Text.txt.txt"

size = os.path.getsize(file_name)

print("File Size:", size, "bytes")

'''11. Write a Python program to write a list to a file.'''

items = ["Python", "Java", "C++", "SQL"]

with open("sample.txt", "w") as file:
    for item in items:
        file.write(item + "\n")

print("List written to file successfully.")

'''12. Write a Python program to copy the contents of a file to another file .'''

with open("Text.txt.txt", "r") as file1:
    content = file1.read()

with open("destination.txt", "w") as file2:
    file2.write(content)

print("File copied successfully.")

'''13. Write a Python program to read a random line from a file.'''

import random

with open("Text.txt.txt", "r") as file:
    lines = file.readlines()

random_line = random.choice(lines)

print("Random Line:", random_line)

'''14. Write a Python program to assess if a file is closed or not.'''

# Open a file
file = open("sample.txt", "r")

# Check if file is closed
print("Is the file closed?", file.closed)

# Close the file
file.close()

# Check again
print("Is the file closed after closing?", file.closed)

'''15.Write a Python program that takes a text file as input and returns the number of words of a given text file.'''

# Open the file in read mode
with open("sample.txt", "r") as file:
    text = file.read()

# Split the text into words
words = text.split()

# Count the number of words
word_count = len(words)

print("Number of words in the file:", word_count)

with open("Text.txt.txt", "r") as file:
    content = file.read()
    print(content)

# with open("Text.txt.txt", "r") as file:
#     lines = file.readlines()
#     print(lines)