# -*- coding: utf-8 -*-
"""Untitled24.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_gb-ILsPG301Zt3FF7r1jQRV8Cc6Nmaa
"""

'''1. Write a Python program to create a class representing a Circle.
  Include methods to calculate its area and perimeter.'''

class Circle:

    def __init__(self, r):
        self.r = r

    def area(self):
        return 3.14 * self.r * self.r

    def perimeter(self):
        return 2 * 3.14 * self.r


c = Circle(5)

print("Area:", c.area())
print("Perimeter:", c.perimeter())

# '''2. Write a Python program to create a person class. Include attributes like name,
#  country and date of birth. Implement a method to determine the person's age.'''

from datetime import date

class Person:

    def __init__(self, name, country, birth_year):
        self.name = name
        self.country = country
        self.birth_year = birth_year

    def age(self):
        current_year = date.today().year
        return current_year - self.birth_year


p = Person("Gopal", "India", 2000)

print("Name:", p.name)
print("Country:", p.country)
print("Age:", p.age())

'''3. Write a Python program to create a calculator class. Include methods for basic  arithmetic operations.'''

class Calculator:

    def add(self, a, b):
        return a + b

    def subtract(self, a, b):
        return a - b

    def multiply(self, a, b):
        return a * b

    def divide(self, a, b):
        return a / b


c = Calculator()

print("Addition:", c.add(10, 5))
print("Subtraction:", c.subtract(10, 5))
print("Multiplication:", c.multiply(10, 5))
print("Division:", c.divide(10, 5))

'''4. Write a Python program to create a class that represents a shape. Include methods to calculate its area and perimeter.
Implement subclasses for different shapes like circle, triangle, and square.'''

class Shape:
    def area(self):
        pass

    def perimeter(self):
        pass


class Circle(Shape):
    def __init__(self, r):
        self.r = r

    def area(self):
        return 3.14 * self.r * self.r

    def perimeter(self):
        return 2 * 3.14 * self.r


class Square(Shape):
    def __init__(self, s):
        self.s = s

    def area(self):
        return self.s * self.s

    def perimeter(self):
        return 4 * self.s


class Triangle(Shape):
    def __init__(self, a, b, c):
        self.a = a
        self.b = b
        self.c = c

    def perimeter(self):
        return self.a + self.b + self.c


c = Circle(5)
s = Square(4)
t = Triangle(3, 4, 5)

print("Circle Area:", c.area())
print("Circle Perimeter:", c.perimeter())

print("Square Area:", s.area())
print("Square Perimeter:", s.perimeter())

print("Triangle Perimeter:", t.perimeter())

'''5. Write a Python program to create a class representing a binary search tree. Include methods for inserting and searching for elements in the binary tree.'''

class TreeNode:
    def __init__(self, key):
        self.key = key
        self.left = None
        self.right = None


class BinarySearchTree:
    def __init__(self):
        self.root = None

    def insert(self, key):
        """Insert a key into the BST."""
        if self.root is None:
            self.root = TreeNode(key)
        else:
            node = self.root
            while True:
                if key < node.key:
                    if node.left is None:
                        node.left = TreeNode(key)
                        break
                    node = node.left
                elif key > node.key:
                    if node.right is None:
                        node.right = TreeNode(key)
                        break
                    node = node.right
                else:
                    break  # Duplicate, not inserting

    def search(self, key):
        """Search for a key in the BST. Returns True if found."""
        node = self.root
        while node is not None:
            if key == node.key:
                return True
            elif key < node.key:
                node = node.left
            else:
                node = node.right
        return False


# Example usage
bst = BinarySearchTree()
bst.insert(10)
bst.insert(5)
bst.insert(15)
bst.insert(3)
bst.insert(7)

print(bst.search(7))  # Output: True
print(bst.search(8))  # Output: False

'''6. Write a Python program to create a class representing a stack data structure. Include methods for pushing and popping elements.'''

class Stack:
    def __init__(self):
        self.items = []

    def push(self, item):
        """Add an item to the top of the stack."""
        self.items.append(item)

    def pop(self):
        """Remove and return the top item from the stack."""
        if not self.is_empty():
            return self.items.pop()
        else:
            raise IndexError("pop from empty stack")

    def peek(self):
        """Return the top item without removing it."""
        if not self.is_empty():
            return self.items[-1]
        else:
            raise IndexError("peek from empty stack")

    def is_empty(self):
        """Check if the stack is empty."""
        return len(self.items) == 0

    def size(self):
        """Return the number of items in the stack."""
        return len(self.items)


# Example usage
s = Stack()
s.push(10)
s.push(20)
s.push(30)

print("Stack size:", s.size())  # Output: 3
print("Top element:", s.peek()) # Output: 30
print("Popped:", s.pop())       # Output: 30
print("Stack size after pop:", s.size())  # Output: 2

'''7. Write a Python program to create a class representing a linked list data structure. Include methods for displaying linked list data, inserting and deleting nodes.'''
class Node:
    def __init__(self, data):
        self.data = data
        self.next = None


class LinkedList:
    def __init__(self):
        self.head = None

    def insert(self, data):
        new_node = Node(data)
        new_node.next = self.head
        self.head = new_node

    def delete(self, key):
        temp = self.head

        if temp is not None and temp.data == key:
            self.head = temp.next
            return

        while temp.next is not None:
            if temp.next.data == key:
                temp.next = temp.next.next
                return
            temp = temp.next

    def display(self):
        temp = self.head
        while temp:
            print(temp.data, end=" -> ")
            temp = temp.next
        print("None")


l = LinkedList()

l.insert(10)
l.insert(20)
l.insert(30)

print("Linked List:")
l.display()

l.delete(20)

print("After Deletion:")
l.display()

'''8. Write a Python program to create a class representing a shopping cart.
Include methods for adding and removing items, and calculating the total price. '''

class ShoppingCart:

    def __init__(self):
        self.items = {}

    def add_item(self, item, price):
        self.items[item] = price

    def remove_item(self, item):
        if item in self.items:
            del self.items[item]

    def total_price(self):
        return sum(self.items.values())


cart = ShoppingCart()

cart.add_item("Apple", 50)
cart.add_item("Milk", 40)
cart.add_item("Bread", 30)

print("Items:", cart.items)
print("Total Price:", cart.total_price())

cart.remove_item("Milk")

print("After removing Milk:")
print("Items:", cart.items)
print("Total Price:", cart.total_price())

'''9. Write a Python program to create a class representing a stack data structure. Include methods for pushing, popping and displaying elements.'''

class Stack:

    def __init__(self):
        self.stack = []

    def push(self, item):
        self.stack.append(item)

    def pop(self):
        if len(self.stack) == 0:
            print("Stack is empty")
        else:
            return self.stack.pop()

    def display(self):
        print("Stack elements:", self.stack)


s = Stack()

s.push(10)
s.push(20)
s.push(30)

s.display()

print("Popped element:", s.pop())

s.display()

'''10. Write a Python program to create a class representing a queue data structure. Include methods for enqueueing and dequeueing elements.'''

class Queue:

    def __init__(self):
        self.queue = []

    def enqueue(self, item):
        self.queue.append(item)

    def dequeue(self):
        if len(self.queue) == 0:
            print("Queue is empty")
        else:
            return self.queue.pop(0)

    def display(self):
        print("Queue elements:", self.queue)


q = Queue()

q.enqueue(10)
q.enqueue(20)
q.enqueue(30)

q.display()

print("Dequeued element:", q.dequeue())

q.display()

'''11. Write a Python program to create a class representing a bank. Include methods for managing customer accounts and transactions.
	Create a Python class called BankAccount which represents a bank account, having as attributes: accountNumber (numeric type),
   name (name of the account owner as string type), balance.'''

	# Create a constructor with parameters: accountNumber, name, balance.
	# Create a Deposit() method which manages the deposit actions.
	# Create a Withdrawal() method which manages withdrawals actions.
	# Create an bankFees() method to apply the bank fees with a percentage of 5% of the balance account.
	# Create a display() method to display account details. Give the complete code for the BankAccount class.

class BankAccount:

    def __init__(self, accountNumber, name, balance):
        self.accountNumber = accountNumber
        self.name = name
        self.balance = balance

    def Deposit(self, amount):
        self.balance = self.balance + amount
        print("Amount Deposited:", amount)

    def Withdrawal(self, amount):
        if amount > self.balance:
            print("Insufficient Balance")
        else:
            self.balance = self.balance - amount
            print("Amount Withdrawn:", amount)

    def bankFees(self):
        fee = self.balance * 0.05
        self.balance = self.balance - fee
        print("Bank Fees Deducted:", fee)

    def display(self):
        print("Account Number:", self.accountNumber)
        print("Account Holder:", self.name)
        print("Balance:", self.balance)


# Creating object
acc = BankAccount(101, "Gopal", 10000)

acc.display()

acc.Deposit(2000)
acc.Withdrawal(1500)
acc.bankFees()

acc.display()

'''12. Build a flashcard using class in python. A flashcard is a card having information on both sides,
which can be used as an aid in memoization. Flashcards usually have a question on one side and an answer on the other.'''

	# Example 1:

	# Approach:

	# Create a class named FlashCard.
	# Initialize dictionary fruits using init() method. Here you have to define fruit name as key and it's color as value. E.g., {"Banana": "yellow", "Strawberries": "pink"}
	# Now randomly choose a pair from fruits by using random module and store the key in variable fruit and value in variable color.
	# Now prompt the user to answer the color of the randomly chosen fruit.
	# If correct print correct else print wrong.
	# Output:

	# welcome to fruit quiz
	# What is the color of Strawberries
	# pink
	# Correct answer
	# Enter 0, if you want to play again: 0
	# What is the color of watermelon
	# green
	# Correct answer
	# Enter 0, if you want to play again: 1

import random

class FlashCard:

    def __init__(self):
        self.fruits = {
            "Banana": "yellow",
            "Strawberries": "pink",
            "Apple": "red",
            "Watermelon": "green",
            "Orange": "orange"
        }

    def play(self):
        fruit, color = random.choice(list(self.fruits.items()))

        print("What is the color of", fruit)
        ans = input()

        if ans.lower() == color:
            print("Correct answer")
        else:
            print("Wrong answer. Correct color is", color)


print("Welcome to fruit quiz")

fc = FlashCard()

while True:
    fc.play()
    choice = input("Enter 0 if you want to play again: ")
    if choice != "0":
        break

'''13. TechWorld, a technology training center, wants to allocate courses for instructors.
 An instructor is identified by name, technology skills, experience and average feedback.
  An instructor is allocated a course, if he/she satisfies the below two conditions:'''

	# eligibility criteria:
	# if experience is more than 3 years, average feedback should be 4.5 or more
	# if experience is 3 years or less, average feedback should be 4 or more
	# he/she should posses the technology skill for the course
	# Identify the class name and attributes to represent instructors. Write a Python program to implement the class chosen with its attributes and methods.

	# Note:

	# Consider all instance variables to be private and methods to be public.
	# An instructor may have multiple technology skills, so consider instance variable, technology_skill to be a list.
	# check_eligibility(): Return true if eligibility criteria is satisfied by the instructor. Else, return false
	# allocate_course(technology): Return true if the course which requires the given technology can be allocated to the instructor. Else, return false.
	# Represent a few objects of the class, initialize instance variables using setter methods, invoke appropriate methods and test your program.
class Instructor:

    def __init__(self):
        self.__name = ""
        self.__technology_skill = []
        self.__experience = 0
        self.__average_feedback = 0

    # Setter methods
    def set_details(self, name, skills, experience, feedback):
        self.__name = name
        self.__technology_skill = skills
        self.__experience = experience
        self.__average_feedback = feedback

    # Check eligibility
    def check_eligibility(self):
        if self.__experience > 3 and self.__average_feedback >= 4.5:
            return True
        elif self.__experience <= 3 and self.__average_feedback >= 4:
            return True
        else:
            return False

    # Allocate course
    def allocate_course(self, technology):
        if self.check_eligibility() and technology in self.__technology_skill:
            return True
        else:
            return False


# Creating objects
inst1 = Instructor()
inst1.set_details("Gopal", ["Python", "Java", "SQL"], 4, 4.6)

inst2 = Instructor()
inst2.set_details("Rahul", ["C", "Java"], 2, 3.8)

# Testing
print("Instructor 1 Eligible:", inst1.check_eligibility())
print("Instructor 1 Course Allocation (Python):", inst1.allocate_course("Python"))

print("Instructor 2 Eligible:", inst2.check_eligibility())
print("Instructor 2 Course Allocation (Java):", inst2.allocate_course("Java"))

'''14. Write a program that uses datetime module within a class. Enter manufacturing date and expiry date of the product.
 The program must display the years, months and days that are left for expiry.'''

from datetime import datetime

class Product:

    def __init__(self, mfg_date, exp_date):
        self.mfg_date = datetime.strptime(mfg_date, "%d-%m-%Y")
        self.exp_date = datetime.strptime(exp_date, "%d-%m-%Y")

    def expiry_left(self):
        today = datetime.today()
        diff = self.exp_date - today

        days = diff.days
        years = days // 365
        months = (days % 365) // 30
        remaining_days = (days % 365) % 30

        print("Time left for expiry:")
        print("Years:", years)
        print("Months:", months)
        print("Days:", remaining_days)


# Input
mfg = input("Enter Manufacturing Date (dd-mm-yyyy): ")
exp = input("Enter Expiry Date (dd-mm-yyyy): ")

p = Product(mfg, exp)

p.expiry_left()

'''15. A university wants to automate their admission process. Students are admitted based on the marks scored in the qualifying exam.
A student is identified by student id, age and marks in qualifying exam. Data are valid, if:'''

	# Age is greater than 20
	# Marks is between 0 and 100 (both inclusive)
	# A student qualifies for admission, if

	# Age and marks are valid and
	# Marks is 65 or more
	# Write a python program to represent the students seeking admission in the university.

class Student:

    def __init__(self, student_id, age, marks):
        self.student_id = student_id
        self.age = age
        self.marks = marks

    def validate_data(self):
        if self.age > 20 and 0 <= self.marks <= 100:
            return True
        else:
            return False

    def check_qualification(self):
        if self.validate_data() and self.marks >= 65:
            return True
        else:
            return False


# Creating objects
s1 = Student(101, 22, 75)
s2 = Student(102, 19, 80)

print("Student 1 Valid:", s1.validate_data())
print("Student 1 Qualified:", s1.check_qualification())

print("Student 2 Valid:", s2.validate_data())
print("Student 2 Qualified:", s2.check_qualification())

'''16. Ice-Cream Scoops and Bowl shop'''

	# Create a class Scoop which has one public property flavor and one private proptery price. Take flavor values during object creation.

	# Create a class Bowl with private prperty scoop_list which will have list of scoopd object.

	# Create a method add_scoops in Bowl class which will add any no of Scoop objects given as parameter and store it in scoops_list.

	# Make getter and setter method for price property.

	# Make a method display to display flavour and price of each Scoop in scoop_list and print total price of the bowl by adding all flavour scoops prices.

	# Make a method sold in both Scoop class and Bowl class to print no of quantity sold.

class Scoop:
    count = 0   # to track scoops sold

    def __init__(self, flavor):
        self.flavor = flavor
        self.__price = 0
        Scoop.count += 1

    # setter for price
    def set_price(self, price):
        self.__price = price

    # getter for price
    def get_price(self):
        return self.__price

    # sold method
    def sold(self):
        print("Scoops sold:", Scoop.count)


class Bowl:
    count = 0   # bowls sold

    def __init__(self):
        self.__scoop_list = []
        Bowl.count += 1

    def add_scoops(self, *scoops):
        for scoop in scoops:
            self.__scoop_list.append(scoop)

    def display(self):
        total = 0
        print("Scoops in Bowl:")
        for scoop in self.__scoop_list:
            print("Flavor:", scoop.flavor, "Price:", scoop.get_price())
            total += scoop.get_price()
        print("Total Price:", total)

    def sold(self):
        print("Bowls sold:", Bowl.count)


# Creating Scoop objects
s1 = Scoop("Vanilla")
s1.set_price(30)

s2 = Scoop("Chocolate")
s2.set_price(40)

s3 = Scoop("Strawberry")
s3.set_price(35)

# Creating Bowl
b = Bowl()

# Adding scoops
b.add_scoops(s1, s2, s3)

# Display bowl details
b.display()

# Sold quantity
s1.sold()
b.sold()

'''17. Create a Bus child class that inherits from the Vehicle class. The default fare charge of any vehicle is seating capacity * 100.
If Vehicle is Bus instance, we need to add an extra 10% on full fare as a maintenance charge.
So total fare for bus instance will become the final amount = total fare + 10% of the total fare.'''

# Note: The bus seating capacity is 50. so the final fare amount should be 5500. You need to override the fare() method of a Vehicle class in Bus class.

class Vehicle:

    def __init__(self, capacity):
        self.capacity = capacity

    def fare(self):
        return self.capacity * 100


class Bus(Vehicle):

    def fare(self):
        basic_fare = super().fare()
        maintenance = basic_fare * 0.10
        total_fare = basic_fare + maintenance
        return total_fare


# Bus seating capacity = 50
b = Bus(50)

print("Total Bus Fare:", b.fare())

'''18. Write a Python class Employee with attributes like emp_id, emp_name, emp_salary, and emp_department and
methods like calculate_emp_salary, emp_assign_department, and print_employee_details.'''

	# Sample Employee Data:
	# "ADAMS", "E7876", 50000, "ACCOUNTING"
	# "JONES", "E7499", 45000, "RESEARCH"
	# "MARTIN", "E7900", 50000, "SALES"
	# "SMITH", "E7698", 55000, "OPERATIONS"

	# Use 'assign_department' method to change the department of an employee.
	# Use 'print_employee_details' method to print the details of an employee.
	# Use 'calculate_emp_salary' method takes two arguments: salary and hours_worked, which is the number of hours worked by the employee. If the number of hours worked is more than 50, the method computes overtime and adds it to the salary. Overtime is calculated as following formula:
	# overtime = hours_worked - 50
	# Overtime amount = (overtime * (salary / 50))

class Employee:

    def __init__(self, emp_name, emp_id, emp_salary, emp_department):
        self.emp_name = emp_name
        self.emp_id = emp_id
        self.emp_salary = emp_salary
        self.emp_department = emp_department

    # Change department
    def emp_assign_department(self, new_dept):
        self.emp_department = new_dept

    # Calculate salary with overtime
    def calculate_emp_salary(self, salary, hours_worked):
        if hours_worked > 50:
            overtime = hours_worked - 50
            overtime_amount = overtime * (salary / 50)
            salary = salary + overtime_amount
        return salary

    # Print employee details
    def print_employee_details(self):
        print("Employee Name:", self.emp_name)
        print("Employee ID:", self.emp_id)
        print("Salary:", self.emp_salary)
        print("Department:", self.emp_department)
        print()


# Creating employee objects
e1 = Employee("ADAMS", "E7876", 50000, "ACCOUNTING")
e2 = Employee("JONES", "E7499", 45000, "RESEARCH")
e3 = Employee("MARTIN", "E7900", 50000, "SALES")
e4 = Employee("SMITH", "E7698", 55000, "OPERATIONS")

# Change department
e1.emp_assign_department("HR")

# Calculate salary with overtime
new_salary = e2.calculate_emp_salary(45000, 55)
e2.emp_salary = new_salary

# Print employee details
e1.print_employee_details()
e2.print_employee_details()
e3.print_employee_details()
e4.print_employee_details()

'''19. Write a Python class Restaurant with attributes like menu_items, book_table, and customer_orders, and methods like add_item_to_menu, book_tables, and customer_order.'''

	# Perform the following tasks now:

	# Now add items to the menu.
	# Make table reservations.
	# Take customer orders.
	# Print the menu.
	# Print table reservations.
	# Print customer orders.
	# Note: Use dictionaries and lists to store the data.

class Restaurant:

    def __init__(self):
        self.menu_items = {}
        self.book_table = []
        self.customer_orders = []

    # add item to menu
    def add_item_to_menu(self, item, price):
        self.menu_items[item] = price

    # book table
    def book_tables(self, table_no):
        self.book_table.append(table_no)

    # customer order
    def customer_order(self, order):
        self.customer_orders.append(order)

    # display menu
    def print_menu(self):
        print("Menu:")
        for item, price in self.menu_items.items():
            print(item, ":", price)

    # display table reservations
    def print_tables(self):
        print("Reserved Tables:", self.book_table)

    # display orders
    def print_orders(self):
        print("Customer Orders:", self.customer_orders)


# create object
r = Restaurant()

# add menu items
r.add_item_to_menu("Pizza", 250)
r.add_item_to_menu("Burger", 150)
r.add_item_to_menu("Pasta", 200)

# book tables
r.book_tables(1)
r.book_tables(3)

# customer orders
r.customer_order("Pizza")
r.customer_order("Burger")

# print details
r.print_menu()
r.print_tables()
r.print_orders()

'''20. Write a Python class BankAccount with attributes like account_number, balance,
 date_of_opening and customer_name, and methods like deposit, withdraw, and check_balance.'''
class BankAccount:

    def __init__(self, account_number, customer_name, balance, date_of_opening):
        self.account_number = account_number
        self.customer_name = customer_name
        self.balance = balance
        self.date_of_opening = date_of_opening

    # deposit method
    def deposit(self, amount):
        self.balance += amount
        print("Deposited:", amount)

    # withdraw method
    def withdraw(self, amount):
        if amount > self.balance:
            print("Insufficient balance")
        else:
            self.balance -= amount
            print("Withdrawn:", amount)

    # check balance
    def check_balance(self):
        print("Current Balance:", self.balance)


# create object
acc = BankAccount("12345", "Gopal", 10000, "10-04-2024")

print("Account Number:", acc.account_number)
print("Customer Name:", acc.customer_name)
print("Date of Opening:", acc.date_of_opening)

acc.deposit(2000)
acc.withdraw(1500)
acc.check_balance()

'''21. Write a Python class Inventory with attributes like item_id, item_name, stock_count, and price,
and methods like add_item, update_item, and check_item_details.'''

class Inventory:

    def __init__(self, item_id, item_name, stock_count, price):
        self.item_id = item_id
        self.item_name = item_name
        self.stock_count = stock_count
        self.price = price

    # add item
    def add_item(self):
        print("Item Added Successfully")

    # update item details
    def update_item(self, new_stock, new_price):
        self.stock_count = new_stock
        self.price = new_price
        print("Item Updated Successfully")

    # check item details
    def check_item_details(self):
        print("\nItem Details")
        print("Item ID:", self.item_id)
        print("Item Name:", self.item_name)
        print("Stock Count:", self.stock_count)
        print("Price:", self.price)


# create object
item1 = Inventory(101, "Laptop", 10, 50000)

# add item
item1.add_item()

# check details
item1.check_item_details()

# update item
item1.update_item(15, 48000)

# check details again
item1.check_item_details()











