# -*- coding: utf-8 -*-
"""PythonFunctionAssingment1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GZhRsK5cXQXFEnbGabroCPCg209mXNEl
"""

'''1. Write a Python function to find the maximum of three numbers.'''

def find_max(a, b, c):
    return max(a, b, c)

print(find_max(10, 20, 15))

def find_max_manual(a, b, c):
    if a >= b and a >= c:
        return a
    elif b >= c:
        return b
    else:
        return c

print(find_max(10, 20, 15))

'''2. Write a Python function to sum all the numbers in a list.'''

	# Sample List : (8, 2, 3, 0, 7)
	# Expected Output : 20

def sum_list(numbers):
    return sum(numbers)

sample = [8, 2, 3, 0, 7]
print(sum_list(sample))  # Output: 20

def sum_list_manual(numbers):
    total = 0
    for num in numbers:
        total += num
    return total

numbers = [8, 2, 3, 0, 7]
print(sum_list_manual(numbers))  # Output: 20

'''3. Write a Python function to multiply all the numbers in a list.'''


	# Sample List : (8, 2, 3, -1, 7)
	# Expected Output : -336

def multiply_list(numbers):
    result = 1
    for num in numbers:
        result *= num
    return result

sample = [8, 2, 3, -1, 7]
print(multiply_list(sample))  # Output: -336

from functools import reduce

def multiply_list_reduce(numbers):
    return reduce(lambda x, y: x * y, numbers, 1)

# Test with sample data
numbers = [8, 2, 3, -1, 7]
print(multiply_list_reduce(numbers))  # Output: -336


# from functools import reduce
# def multiply_list_reduce(numbers):
#     return reduce(lambda x, y: x * y, numbers, 1)

'''4. Write a Python function to reverse a string.'''

	# Sample String : "1234abcd"
	# Expected Output : "dcba4321"

def reverse_string(s):
    return s[::-1]

sample = "1234abcd"
print(reverse_string(sample))  # Output: "dcba4321"

# def reverse_string_manual(s):
#     return ''.join(reversed(s))

def reverse_string_manual(s):
    return ''.join(reversed(s))

sample = "1234abcd"
print(reverse_string_manual(sample))  # Output: "dcba4321"

'''5. Write a Python function to check whether a number falls within a given range.'''


def check_range(num, start, end):
    if num in range(start, end+1):
        print(f"{num} is in the range")
    else:
        print(f"{num} is not in the range")

check_range(12, 10, 20)

'''6. Write a Python function that accepts a string and counts the number of upper and lower case letters'''

	# Sample String : 'The quick Brow Fox'

	# Expected Output :
	# No. of Upper case characters : 3
	# No. of Lower case Characters : 12

def count_case_letters(text):
    upper = sum(1 for ch in text if ch.isupper())
    lower = sum(1 for ch in text if ch.islower())

    print("No. of Upper case characters :", upper)
    print("No. of Lower case characters :", lower)

count_case_letters('The quick Brow Fox')

'''7. Write a Python function that takes a list and returns a new list with distinct elements from the first list.'''

	# Sample List : [1,2,3,3,3,3,4,5]
	# Unique List : [1, 2, 3, 4, 5]

def unique_list(lst):
    return list(set(lst))

sample_list = [1,2,3,3,3,3,4,5]
print("Unique List:", unique_list(sample_list))

'''8. Write a Python function that checks whether a passed string is a palindrome or not.'''
def check_palindrome(text):
  if text == text[:: -1]:
    print("The String is a palindrome")
  else:
    print("The string is not a palindrome")
check_palindrome("madam")

'''9. Write a Python program that accepts a hyphen-separated sequence of words as input and prints the words
in a hyphen-separated sequence after sorting them alphabetically.'''

	# Sample Items : green-red-yellow-black-white
	# Expected Result : black-green-red-white-yellow

def sort_words(sequence):
    # split the string into a list using hyphen
    words = sequence.split('-')

    # sort the list alphabetically
    words.sort()

    # join the words again using hyphen
    result = '-'.join(words)

    print(result)


# Example
items = "green-red-yellow-black-white"
sort_words(items)

'''10. Write a Python program to detect the number of local variables declared in a function.'''

def count_locals():
    a = 10
    b = 20
    c = a + b
    d = "Python"

    print("Number of local variables:", len(locals()))

count_locals()

'''11. Write a Python program to create a lambda function that adds 15 to a given number passed in as an argument,
 also create a lambda function that multiplies argument x with argument y and prints the result.'''

add_15 = lambda x: x + 15
multiply = lambda x, y: x * y

print("Add 15:", add_15(10))
print("Multiplication:", multiply(4, 5))

'''12. Write a Python program to create a function that takes one argument, and that argument will be multiplied with an unknown given number.'''
# Sample Output:
# 	Double the number of 15 = 30
# 	Triple the number of 15 = 45
# 	Quadruple the number of 15 = 60
# 	Quintuple the number 15 = 75


def multiplier(n):
    def multiply(x):
        return x * n
    return multiply


double = multiplier(2)
triple = multiplier(3)
quadruple = multiplier(4)
quintuple = multiplier(5)

print("Double the number of 15 =", double(15))
print("Triple the number of 15 =", triple(15))
print("Quadruple the number of 15 =", quadruple(15))
print("Quintuple the number 15 =", quintuple(15))

'''13. Write a Python program to sort a list of tuples using Lambda.'''

	# Original list of tuples:
	# [('English', 88), ('Science', 90), ('Maths', 97), ('Social sciences', 82)]
	# Sorting the List of Tuples:
	# [('Social sciences', 82), ('English', 88), ('Science', 90), ('Maths', 97)]

  # Original list
marks = [('English', 88), ('Science', 90), ('Maths', 97), ('Social sciences', 82)]

# Sort using lambda (based on second element of tuple)
sorted_marks = sorted(marks, key=lambda x: x[1])

print("Sorting the List of Tuples:")
print(sorted_marks)

'''15. Write a Python program to filter a list of integers using Lambda.'''

	# Original list of integers:
	# [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
	# Even numbers from the said list:
	# [2, 4, 6, 8, 10]
	# Odd numbers from the said list:
	# [1, 3, 5, 7, 9]

  # Original list
numbers = [1,2,3,4,5,6,7,8,9,10]

# Filter even numbers
even_numbers = list(filter(lambda x: x % 2 == 0, numbers))

# Filter odd numbers
odd_numbers = list(filter(lambda x: x % 2 != 0, numbers))

print("Original list of integers:")
print(numbers)

print("Even numbers from the said list:")
print(even_numbers)

print("Odd numbers from the said list:")
print(odd_numbers)

'''16. Write a Python program to square and cube every number in a given list of integers using Lambda.'''

	# Original list of integers:
	# [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
	# Square every number of the said list:
	# [1, 4, 9, 16, 25, 36, 49, 64, 81, 100]
	# Cube every number of the said list:
	# [1, 8, 27, 64, 125, 216, 343, 512, 729, 1000]

# Original list
numbers = [1,2,3,4,5,6,7,8,9,10]

# Square every number
square_numbers = list(map(lambda x: x**2, numbers))

# Cube every number
cube_numbers = list(map(lambda x: x**3, numbers))

print("Original list of integers:")
print(numbers)

print("Square every number of the said list:")
print(square_numbers)

print("Cube every number of the said list:")
print(cube_numbers)

'''18. Write a Python program to find if a given string starts with a given character using Lambda.'''
# Lambda function
starts_with = lambda string, ch: string.startswith(ch)

# Example
text = "Python"
character = "P"

print(starts_with(text, character))

'''19. Write a Python program to rearrange positive and negative numbers in a given array using Lambda.'''

	# Original arrays:
	# [-1, 2, -3, 5, 7, 8, 9, -10]
	# Rearrange positive and negative numbers of the said array:
	# [2, 5, 7, 8, 9, -10, -3, -1]
# Original array
numbers = [-1, 2, -3, 5, 7, 8, 9, -10]

# Rearrange using lambda (positive first, then negative)
result = sorted(numbers, key=lambda x: (x < 0, x))

print("Original arrays:")
print(numbers)

print("Rearrange positive and negative numbers of the said array:")
print(result)

'''20. Write a Python program to count the even and odd numbers in a given array of integers using Lambda.'''

	# Original arrays:
	# [1, 2, 3, 5, 7, 8, 9, 10]
	# Number of even numbers in the above array: 3
	# Number of odd numbers in the above array: 5

  # Original array
numbers = [1, 2, 3, 5, 7, 8, 9, 10]

# Count even numbers
even_count = len(list(filter(lambda x: x % 2 == 0, numbers)))

# Count odd numbers
odd_count = len(list(filter(lambda x: x % 2 != 0, numbers)))

print("Original arrays:")
print(numbers)

print("Number of even numbers in the above array:", even_count)
print("Number of odd numbers in the above array:", odd_count)

'''21. Write a Python program to find numbers divisible by nineteen or thirteen from a list of numbers using Lambda.'''

	# Orginal list:
	# [19, 65, 57, 39, 152, 639, 121, 44, 90, 190]
	# Numbers of the above list divisible by nineteen or thirteen:
	# [19, 65, 57, 39, 152, 190]

# Original list
numbers = [19, 65, 57, 39, 152, 639, 121, 44, 90, 190]

# Filter numbers divisible by 19 or 13
result = list(filter(lambda x: x % 19 == 0 or x % 13 == 0, numbers))

print("Original list:")
print(numbers)

print("Numbers of the above list divisible by nineteen or thirteen:")
print(result)

'''22. Write a Python program to check whether a given string contains a capital letter,
a lower case letter, a number and a minimum length using lambda.'''
# Lambda function to validate string
check_string = lambda s: (
    any(c.isupper() for c in s) and
    any(c.islower() for c in s) and
    any(c.isdigit() for c in s) and
    len(s) >= 8
)

# Example string
text = "Python123"

if check_string(text):
    print("Valid string")
else:
    print("Invalid string")

